# Yarn 4 configuration
nodeLinker: node-modules

# Enable checksum validation and faster installs
checksumBehavior: throw

# Avoid scripts unless needed
enableScripts: true

# Use --immutable flag in CI/Docker instead of config (removed in Yarn 4)

# Compression settings for Yarn cache
compressionLevel: 6
